spring.application.name=ai-service
server.port=8084

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


########################################
# Ollama Configuration
########################################

ollama.base-url=http://localhost:11434
ollama.model=qwen2.5
ollama.chat-endpoint=/api/chat
ollama.timeout=300000